### ISSUE TITLE
When I use q to go back the position, with NERDTree, postion is wrong.

### ISSUE THREAD

**Issue by yujunhui** [echuraev/translate-shell.vim#10]
1. open vim
2. open NERDTree
3. open file
4. translate some text
5. hit q to close the translation result window
6. the postion go to the NERDTree dir. It should go back to the file I open before.

**Comment by echuraev** [comment]
Hi @yujunhui!

Thank you for your feedback. There is nothing wrong in this behavior. Just by default vim moves cursor after closing window to the window on the left side. I'll take a look what can I do for fixing this.

**Comment by yujunhui** [comment]
@echuraev Thanks a lot. 
>  Just by default vim moves cursor after closing window to the window on the left side.

I only know about it now.

**Comment by echuraev** [comment]
@yujunhui I implemented this functionality for returning to previous window when you close translate window. Please check it. I committed this change to master. Please let me know how it works for you.
