### ISSUE TITLE
Feature request - floating window support

### ISSUE THREAD

**Issue by weilbith** [echuraev/translate-shell.vim#13]
Hey, thanks for the nice plugin. 👏
I would like to ask what do you think about using a floating window for `:Trans`? So maybe just add another option for `g:trans_win_position` with `float`? That would be awesome!

**Comment by echuraev** [comment]
Hello Thore!
I thought about it and about adding this feature to the plugin but unfortunately I don't have enough free time to do it. I don't know when I'll have time to do it. But if you wish you could try to do it and create a PR. I'll be able to help you with any questions.

**Comment by weilbith** [comment]
Okay cool. Should be fairly easy enough. Let's see when I find time. :grimacing:

**Comment by echuraev** [comment]
Nice! Thank you! Please, let me know if you will have any questions.

**Comment by weilbith** [comment]
Sorry, but I just switched to `voldikss/vim-translator` which supports this feature. :see_no_evil: 
Closing the issue for now as there seem to be no further interest.
