### ISSUE TITLE
Do not open buffer if result is empty

### ISSUE THREAD

**Issue by oblitum** [echuraev/translate-shell.vim#3]
First of all, awesome plugin. I'd like to suggest to not open the translate window if the translation result is empty, more importantly for me is because I've just installed the plugin and the first thing I tried was text-to-speech with `:Trans -no-translate -speak`, so I just wanted to hear audio without any text output, but despite that the translation window was open and I had to close it.

Another suggestion is to provide <kbd>q</kbd> as a default mapping in the translation window, for closing it. It's common that file manager plugins to do that (like [vimfiler](https://github.com/Shougo/vimfiler.vim) for example, Goyo also does this).

**Comment by echuraev** [comment]
Hey Francisco!
Thank you for your feedback! It is very good ideas not to open translate buffer when it's empty and close it by pressing `q`. I'll do it soon when I'll have free time. May be on the next week.

**Comment by oblitum** [comment]
@echuraev OK thanks! Another thing that came to mind for me would be to [unify `:Trans` and `:TransVisual` into a single command](https://stackoverflow.com/a/18897835/1000282)? I'm not sure why there are two of them. I have some commands on my `.vimrc` for example, that work with ranges and if the range is empty it just do an unitary thing.

**Comment by echuraev** [comment]
@oblitum Yes I thought about it and tried to use `:Trans` and `:TransVisual` in a single command. But I faced several problems. I have this task in my backlog. May be I'll try to do it together with request from your previous message.
Thank you for your feedback! It helps to do the plugin better.

**Comment by oblitum** [comment]
@echuraev OK. [The link I've provided above](https://stackoverflow.com/a/18897835/1000282) can be of some help.

**Comment by echuraev** [comment]
Resolve in #4 
I think it is better to try to unify translate functions in another pull request and connect it with another issue. I think, I'll try to do it when I'll have free time.
@oblitum Thank you one again for your great ideas!

**Comment by oblitum** [comment]
Thanks!
