### ISSUE TITLE
Trans -brief doesn't respect g:trans_default_direction

### ISSUE THREAD

**Issue by oblitum** [echuraev/translate-shell.vim#6]
`:Trans :pt -brief` works correctly for displaying brief Portuguese translation but simply `:Trans -brief` just brings the original text, despite having configured `let g:trans_default_direction = ":pt"`. Full translation result (simply `:Trans`, without `-brief`) respects it.

**Comment by echuraev** [comment]
@oblitum Thank you! I'll take a look on it.

**Comment by echuraev** [comment]
@oblitum thank you for your point.
I did it on purpose. I thought that if user wants to pass some additional options to the `:Trans` then he can change and the target language. So user have to pass target language with the additional options.
Do you think that it is better to keep `g:trans_default_direction` with the additional arguments?
I think I'll add parsing of additional options to `:Trans` and if user doesn't specify the target language then I'll use `g:trans_default_direction`.

**Comment by oblitum** [comment]
@echuraev that seems a good approach. I know what you mean, but for me at least, it seemed natural that the configured defaults would work as fallback when not passed as arguments, regardless of passing additional options or not.

**Comment by echuraev** [comment]
@oblitum it makes sense. Thank you! I'll take a look on it.

**Comment by echuraev** [comment]
Fixed it in release 2.0.1 :)
